auth/auth_app/urls.py
from django.conf.urls import url
from auth.auth_app import views

 #TEMPLATE URLS

app_name = 'auth_app'

urlpatterns = [
    url(r"^register/$", views.register, name='register'),
    url(r'user_login/$', views.user_login, name='user_login'),
]

auth/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from auth.auth_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^basic_app/', include('auth.auth_app.urls'))
]

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

</head>
    <nav  class="navbar navbar-expand-md navbar-light bg-dark navbar-fixed-top">
        <div class="collapse navbar-collapse justify-content-between"id="nav">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand text-light font-weight-bold text-uppercase px-3" href="{% url 'index' %}">Django </a></li>
                <li><a  class="nav-link text-light " href="{% url 'admin:index' %}">Admin</a></li>
                <li><a  class="nav-link text-light " href="{% url 'auth_app:register' %}">Register</a></li>

                {% if user.is_authenticated %}
                <li><a class='nav-link text-light' href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                <li><a class='nav-link text-light' href="{% url 'auth_app:user_login' %}">Login</a></li>
                {% endif %}





            </ul>
        </div>
   </nav>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>
</html>

templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Authentification example</h1>
</div>

{% endblock %}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

    <div class="jumbotron">
        <h1>Please Login </h1>
        <form action="{% url 'auth_app:user_login' %}" method="post">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Entrer Username">

            <label for="password">Password:</label>
            <input type="password" name="password" placeholder="password">

            <input type="submit" name="" value="Login">
        </form>
    </div>

{% endblock %}

templates/basic_app/registrer.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}

    <div class="jumbotron">
        {% if registered %}
            <h1> Thank you for registering !! </h1>
        {% else %}
            <h3> Fill out the form: </h3>

            <form enctype="multipart/form-data" method="post" >
                {% csrf_token %}
                {{ user_form.as_p }}
                {{ profile_form.as_p }}
                <input type="submit" name="" value="Register">
            </form>
        {% endif %}
    </div>
{% endblock %}